using System;

namespace Advice.Logging
{
    public class IndexType
    {
        public string Index { get; private set; }
        public string Type { get; private set; }

        public IndexType(string index, string type)
        {
            Index = index;
            Type = type;
        }
    }
    public static class ElkIndexTypeProvider
    {
        public static readonly IndexType ExceptionsException = new IndexType("exceptions", "exception");
        public static readonly IndexType ErrorsError = new IndexType("errors", "error");
        public static readonly IndexType DefautsDefault = new IndexType("defaults", "default");
        public static readonly IndexType EventsTasklog = new IndexType("events", "tasklog");
        public static readonly IndexType ServiceReviewService = new IndexType("servicereviewservice", "servicereview");
        public static readonly IndexType NoaGeneratedCalls = new IndexType("autogeneratedcalls", "noa");
        public static readonly IndexType NonNoaGeneratedCalls = new IndexType("autogeneratedcalls", "non-noa");
    }
}
