using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Advice.Domain.Entities.Enums
{
    public enum PermissionsEnum
    {
        CreateNewTask = 1,
        CreateNewTaskOtherUser = 2,
        ReAssignTaskToEsAdvisor = 3,
        ReAssignTaskToEsa = 4,
        ReAssignTaskToEsSupportConsultant = 5,
        ReAssignTaskToEsCaseHandler = 6,
        ReAssignTaskToEsTeamLeader = 7,
        ReAssignTaskToEsManager = 8,
        EditTaskOwnTask = 9,
        EditTaskOtherUser = 10,
        DeleteTaskOwn = 11,
        DeleteTaskOtherUser = 12,
        ResetTask = 13,
        CompleteOwnTask = 14,
        CompleteOtherUserTask = 15,
        ViewOtherTaskLists = 16,
        AddNewJob = 17,
        AddNewAction = 18,
        EditActionAll = 19,
        EditActionInternalNotes = 20,
        EditJobDetails = 21,
        DeleteAction = 22,
        DeleteJob = 23,
        MoveAction = 24,
        MoveJob = 25,
        CreateGeneralContact = 26,
        CreateAuthorisedContact = 27,
        EditGeneralContact = 30,
        EditAuthorisedContact = 31,
        CreateAdviceNote = 32,
        EditAdviceNote = 33,
        DeleteAdviceNote = 34,
        EditUser = 35,
        ChangeUserTeam = 36,
        ChangeUserRole = 37,
        ProcessEmailInbox = 38,
        BulkReassignRecipient = 39,
        BypassCallerNameCheck = 43,
        ModifyActionOtherUser = 44,
        ReAssignTaskToCentralAdministration = 45,
        ReAssignTaskToNonEsOvertimeWorker = 46,
        ReAssignTaskToRoiNiClientServices = 47,
        ReAssignTaskToRoiNiTraineeAdvisor = 48,
        ReAssignTaskToTaxWiseUser = 49,
        ReAssignTaskToTaxWiseManager = 50,
        ReAssignTaskToHsAdvisor = 51,
        ViewOutOfHoursTaskList = 52,
        ReAssignTaskToEsSpecialProjects = 53,
        ReAssignTaskToEsOutofHoursUser = 54,
        ReAssignTaskToReadOnly = 55,
        ModifyJobOtherUser = 56,
        EditContactType = 57,
        ViewHsOutOfHoursTeam = 58,
        ViewSuspendedClient = 59,
        ReAssignTaskToHsOutofHoursUser = 60,
        ReAssignTaskToHsManager = 61,
        ReAssignTaskToHsSpecialProjects = 62,
        ReAssignTaskToHsTeamLeader = 63,
        AccessCallRecorder = 64,
        ViewQa = 65,
        AddQa = 66,
        EditQa = 67,
        DeleteQa = 68,
        ActionTyperestrictedtoInternal = 69,
        ViewGraphitePremiumClient = 70,
        AddGraphiteConsultancyAction = 71,
        ViewPeninsulaClient = 72,
        DeleteAdviceContact = 73

    }
}
