using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Advice.Domain.Entities.Enums
{
    public enum ServiceReviewCanGroupIds : short
    {
        AA_AB = 1,
        AC_AD = 2,
        AE_AK = 3,
        AL = 4,
        AM_AN = 5,
        AO_AR = 6,
        AS_AZ = 7,
        BA_BD = 8,
        BE_BK = 9,
        BL_BN = 10,
        BO_BP = 11,
        BQ_BR = 12,
        BS_BZ = 13,
        CA_CD = 14,
        CE_CG = 15,
        CH_CK = 16,
        CL_CO = 17,
        CP_CZ = 18,
        DA = 19,
        DB_DI = 20,
        DJ_Dz = 21,
        EA_EQ = 22,
        ER_EZ = 23,
        FA_FM = 24,
        FN_FZ = 25,
        GA_GD = 26,
        GE = 27,
        GF_GN = 28,
        GO_GZ = 29,
        HA = 30,
        HB_HE = 31,
        HF_HK = 32,
        HL_HZ = 33,
        IA_IM = 34,
        IN_IZ = 35,
        JA_JZ = 36,
        KA_KZ = 37,
        LA_LZ = 38,
        MA_MD = 39,
        ME_MH = 40,
        MI = 41,
        MJ_MZ = 42,
        NA_NE = 43,
        NF_NZ = 44,
        OA_OZ = 45,
        PA = 46,
        PB_PE = 47,
        PF_PQ = 48,
        PR_PZ = 49,
        QA_QZ = 50,
        RA_RD = 51,
        RE = 52,
        RF_RN = 53,
        RO_RZ = 54,
        SA_SD = 55,
        SE_SF = 56,
        SG_SI = 57,
        SJ_SO = 58,
        SP_SS = 59,
        ST = 60,
        SU_SV = 61,
        SW_SZ = 62,
        TA_TH = 63,
        TI_TL = 64,
        TM_TO = 65,
        TP_TR = 66,
        TS_TZ = 67,
        UA_UZ = 68,
        VA_VZ = 69,
        WA_WD = 70,
        WE_WN = 71,
        WO_WZ = 72,
        XA_XZ = 73,
        YA_YZ = 74,
        ZA_ZZ = 75,
        Numbers_0_9 = 76
    }
    
}

