using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Advice.AutoGeneratedCallService.Contracts
{
    public interface INoaAutoGenerateCallService
    {
        void GenerateTasks();
    }
}
