//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Peninsula.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Peninsula.Domain.Entities;
    
    public partial class PeninsulaEntities : DbContext
    {
        public PeninsulaEntities()
            : base("name=PeninsulaDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCustomer> TBLCustomers { get; set; }
        public virtual DbSet<TBLSiteAddress> TBLSiteAddresses { get; set; }
        public virtual DbSet<TBLSiteAddressSiteAddressType> TBLSiteAddressSiteAddressTypes { get; set; }
        public virtual DbSet<TBLCompanyContact> TBLCompanyContacts { get; set; }
    }
}
