//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peninsula.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSiteAddress
    {
        public TBLSiteAddress()
        {
            this.TBLSiteAddressSiteAddressTypes = new HashSet<TBLSiteAddressSiteAddressType>();
        }
    
        public int SiteAddressID { get; set; }
        public int SiteAddressTypeID { get; set; }
        public string CustomerKey { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string PhoneMain { get; set; }
        public string FaxMain { get; set; }
        public string HSConsultantCode { get; set; }
        public string PersonnelConsultantCode { get; set; }
        public string SalesConsultantCode { get; set; }
        public Nullable<bool> flagHidden { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string SoundXCompanyName { get; set; }
        public string SoundXAddress1 { get; set; }
        public string SoundXPostCode { get; set; }
        public string CurrentHSConsultant { get; set; }
        public string CurrentPersonnelConsultant { get; set; }
        public string CurrentSalesRepUserName { get; set; }
        public int LegalLocationID { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> IndustryTypeID { get; set; }
        public Nullable<int> PrincipleBusinessTypeID { get; set; }
        public Nullable<bool> PrivateAndConfidential { get; set; }
        public string HopewiserIndustryType { get; set; }
        public Nullable<int> CompanyNo { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public bool LockCurrentHSConsultant { get; set; }
        public string OperaCompanyName { get; set; }
        public string CompanyNameJustAlphaNumeric { get; set; }
    
        public virtual ICollection<TBLSiteAddressSiteAddressType> TBLSiteAddressSiteAddressTypes { get; set; }
    }
}
