//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peninsula.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSiteAddressSiteAddressType
    {
        public int SiteAddressID { get; set; }
        public int SiteAddressTypeID { get; set; }
    
        public virtual TBLSiteAddress TBLSiteAddress { get; set; }
    }
}
