//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionTypeGroup
    {
        public long ActionTypeGroupId { get; set; }
        public long ActionTypeId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ActionType ActionType { get; set; }
    }
}
