//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessWiseTask : Task
    {
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<long> JusrisdictionID { get; set; }
        public string JusrisdictionDescription { get; set; }
        public string IndividualOrGroup { get; set; }
        public string IndividualForename { get; set; }
        public string IndividualSurname { get; set; }
        public string GroupName { get; set; }
        public string BusinessWiseOrTelephone { get; set; }
        public Nullable<System.DateTime> PreferedDateOfContact { get; set; }
        public string PreferedTimeOfContact { get; set; }
        public Nullable<long> BusinessWiseNatureOfAdviceGroupId { get; set; }
        public Nullable<long> AuthorisedUserID { get; set; }
    
        public virtual BusinessWiseNatureOfAdviceGroup BusinessWiseNatureOfAdviceGroup { get; set; }
    }
}
