//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int DivisionId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
    }
}
