//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HroTask : Task
    {
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<long> JusrisdictionID { get; set; }
        public string JusrisdictionDescription { get; set; }
        public string IndividualOrGroup { get; set; }
        public string IndividualForename { get; set; }
        public string IndividualSurname { get; set; }
        public string GroupName { get; set; }
        public string ResponseType { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string ResponseTime { get; set; }
        public Nullable<long> HroNatureOfAdviceGroupId { get; set; }
        public Nullable<System.Guid> HroUserID { get; set; }
        public string ResponseEmail { get; set; }
        public Nullable<int> HroEmployeeId { get; set; }
    
        public virtual BusinessWiseNatureOfAdviceGroup HroNatureOfAdviceGroup { get; set; }
    }
}
