//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReassignTaskEvent
    {
        public long Id { get; set; }
        public long TaskId { get; set; }
        public Nullable<long> PreviousTeamId { get; set; }
        public Nullable<long> NewTeamId { get; set; }
        public string PreviousUser { get; set; }
        public string NewUser { get; set; }
        public Nullable<long> ReasonId { get; set; }
        public string Comment { get; set; }
        public string ReassignedBy { get; set; }
        public Nullable<System.DateTime> ReassignedDate { get; set; }
    
        public virtual Team NewTeam { get; set; }
        public virtual Team PreviousTeam { get; set; }
        public virtual TaskModifyingReason TaskModifyingReason { get; set; }
        public virtual Task Task { get; set; }
    }
}
