//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceReviewServiceCanGroup
    {
        public ServiceReviewServiceCanGroup()
        {
            this.ServiceReviewServiceSchedules = new HashSet<ServiceReviewServiceSchedule>();
        }
    
        public short ServiceReviewServiceCansGroupId { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
        public string Regex { get; set; }
    
        public virtual ICollection<ServiceReviewServiceSchedule> ServiceReviewServiceSchedules { get; set; }
    }
}
