//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModifyingReason
    {
        public TaskModifyingReason()
        {
            this.Tasks = new HashSet<Task>();
            this.TaskArchives = new HashSet<TaskArchive>();
            this.ReassignTaskEvents = new HashSet<ReassignTaskEvent>();
        }
    
        public long TaskModifyingReasonID { get; set; }
        public long TaskModifyingReasonGroupID { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual TaskModifyingReasonGroup TaskModifyingReasonGroup { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TaskArchive> TaskArchives { get; set; }
        public virtual ICollection<ReassignTaskEvent> ReassignTaskEvents { get; set; }
    }
}
