//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.ReassignTaskEvents = new HashSet<ReassignTaskEvent>();
            this.ReassignTaskEvents1 = new HashSet<ReassignTaskEvent>();
            this.TaskArchives = new HashSet<TaskArchive>();
        }
    
        public long TeamID { get; set; }
        public string Description { get; set; }
        public long ManagerID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<int> DivisionId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ReassignTaskEvent> ReassignTaskEvents { get; set; }
        public virtual ICollection<ReassignTaskEvent> ReassignTaskEvents1 { get; set; }
        public virtual ICollection<TaskArchive> TaskArchives { get; set; }
        public virtual Division Division { get; set; }
        public virtual Department Department { get; set; }
    }
}
