//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Teams = new HashSet<Team>();
            this.CorporatePriorities = new HashSet<CorporatePriority>();
            this.MaintenanceUserPermissions = new HashSet<MaintenanceUserPermission>();
        }
    
        public long UserID { get; set; }
        public string Username { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> RoleID { get; set; }
        public Nullable<long> TeamID { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<CorporatePriority> CorporatePriorities { get; set; }
        public virtual ICollection<MaintenanceUserPermission> MaintenanceUserPermissions { get; set; }
    }
}
