using System;
using System.Collections.Generic;
using System.Linq;
using Advice.AutoGeneratedCallService.Contracts;
using Advice.Domain.Entities;
using Advice.Domain.Entities.Enums;
using Advice.Domain.Entities.Parameters;
using Advice.Domain.RepositoryContracts;

namespace Advice.AutoGeneratedCallService.Implementations
{
    public class NonNoaAutoGenerateCallService : AutoGenerateCallService, INonNoaAutoGenerateCallService
    {        
        public NonNoaAutoGenerateCallService(IJobRepository jobRepository, ITaskRepository taskRepository,ICustomEntityRepository customEntityRepository)
            :base( jobRepository,  taskRepository, customEntityRepository)
        {}
        protected override IEnumerable<Job> GetJobsForWorkingGroup()
        {
            return _jobRepository.GetOpenJobsForWorkingUserGroupByNonNatureOfAdviceGroupAndLastActionDate(DateTime.Today.AddDays(-30));
        }
        protected override IEnumerable<Job> GetJobs()
        {  
            var returnedJobs = _jobRepository.GetOpenJobsByNonNatureOfAdviceGroupAndLastActionDate(DateTime.Today.AddDays(-30));
            return returnedJobs;
        }
    }
}
