using System;
using System.Reflection;
using Advice.AutoGeneratedCallService.Common;
using Advice.AutoGeneratedCallService.Contracts;
using Advice.Logging;
using Advice.Logging.Contracts;


namespace Advice.AutoGeneratedCallService
{
    class Program
    {
        public static readonly IElkLog Log = ElkLogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        static void Main(string[] args)
        {             
            var container = IocConfig.Setup();
            var autoGenerateCall = container.GetInstance<IAutoGenerateCall>();
            autoGenerateCall.Run();
        }
    }
}
