using Advice.Data.Common;
using Advice.Data.Contracts;
using Advice.Data.Repository;
using Advice.Domain.RepositoryContracts;
using StructureMap.Configuration.DSL;

namespace Advice.AutoGeneratedCallService.Common
{
    public class AdviceDataRegistry : Registry
    {
        public AdviceDataRegistry()
        {
            For<IAdviceDbContextManager>().Use<AdviceDbContextManager>();           
            
            For<ITaskRepository>().Use<TaskRepository>();
            For<IJobRepository>().Use<JobRepository>();
            For<ICustomEntityRepository>().Use<CustomEntityRepository>();
            For<ITaskStoredProcRunner>().Use<TaskStoredProcRunner>();
            //For<IUserRepository>().Use<UserRepository>();

            // UNCOMMENT FOR DEV TESTING
            // TODO: put behind config switch
            //For<IExchangeEmailService>().Use<MockExchangeEmailService>();
        }
    }
}
