using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Advice.AutoGeneratedCallService.Contracts;
using Advice.AutoGeneratedCallService.Implementations;
using StructureMap.Configuration.DSL;

namespace Advice.AutoGeneratedCallService.Common
{
    public class AutoCallGenerateDataRegistry : Registry
    {
        public AutoCallGenerateDataRegistry()
        {
            For<IAutoGenerateCall>().Use<AutoGenerateCall>();
            For<INoaAutoGenerateCallService>().Use<NoaAutoGenerateCallService>();
            For<INonNoaAutoGenerateCallService>().Use<NonNoaAutoGenerateCallService>();

            Configure(x => x.ImportRegistry(typeof (AdviceDataRegistry)));
        }
    }
}